!!dev.wuffs.squatgrow.config.SquatGrowConfig
ae2Multiplier: 2
allowAdventureTwerking: true
chance: 0.1
debug: false
enableAE2Accelerator: true
enableDirtToGrass: false
enableMysticalCrops: true
hoeTakesDamage: true
ignoreList: ['minecraft:grass_block', 'minecraft:grass', 'minecraft:tall_grass', 'minecraft:netherrack',
  'minecraft:warped_nylium', 'minecraft:crimson_nylium']
randomTickMultiplier: 2
range: 2
requireHoe: true
requirements:
  durabilityDamage: 1
  enabled: true
  equipmentRequirement: {}
  heldItemRequirement: []
  requiredEnchantment: ''
  requiredItemTakesDamage: false
sugarcaneMultiplier: 4
useWhitelist: false
