#Changes who stages are granted to when using the gamestages api
#Changes who stages are removed from when using the gamestages api
#Allowed Values: PLAYER, TEAM, BOTH
change = "TEAM"
#Changes who's stages are checked when using the gamestages api
#Allowed Values: PLAYER, TEAM, BOTH
check = "BOTH"
#Changes who's stages are listed by the gamestages api
#Allowed Values: PLAYER, TEAM, BOTH
list = "BOTH"

