#Maximum number of pets a player can have (-1 for infinite)
#Range: > -1
max_pets = -1
#Whether the max number of pets a player can have is total or only following pets
pets_following = false
#Whether the remove pet screen will open when shift right clicking a pet
can_remove = false
#Whether the invincibility is for only pets, or any tamable animal (such as horses). These other animals do NOT count towards total pets.
only_pets = false

